### ISSUE TITLE
Create Skeleton Umbrella App

### ISSUE THREAD

**Issue by mjcloutier** [mjcloutier/template_ex#1]
1. Phoenix Umbrella App
2. Create 5 Apps (cd apps)
- [x] Admin: `mix phx.new admin --app admin --no-ecto`
- [x] DB: `mix new database --app database --sup`
- [x] API: `mix phx.new api --app api --no-webpack --no-html --no-ecto`
- [x] Aggregator: `mix new aggregator --app aggregator --sup`
- [x] Webhook: `mix phx.new webhook --app webhook --no-webpack --no-html --no-ecto`

**Comment by mjcloutier** [comment]
Completed in Initial Commit
